export const allRoles: Record<string, string[]> = {
  customer: ['account:read', 'account:write', 'order:read', 'prescription:write'],
  staff: [
    'account:read',
    'product:read',
    'order:read',
    'order:update',
    'inventory:read',
    'inquiry:read',
  ],
  pharmacist: [
    'account:read',
    'product:read',
    'order:read',
    'order:update',
    'prescription:read',
    'prescription:update',
    'inventory:read',
    'inventory:write',
  ],
  manager: [
    'account:read',
    'product:read',
    'product:write',
    'product:update',
    'category:read',
    'category:write',
    'brand:read',
    'brand:write',
    'order:read',
    'order:update',
    'prescription:read',
    'prescription:update',
    'inventory:read',
    'inventory:write',
    'content:read',
    'content:write',
    'settings:read',
    'customer:read',
    'dashboard:read',
  ],
  admin: [
    'account:read',
    'account:write',
    'product:read',
    'product:write',
    'product:update',
    'product:delete',
    'category:read',
    'category:write',
    'category:update',
    'category:delete',
    'brand:read',
    'brand:write',
    'brand:update',
    'brand:delete',
    'order:read',
    'order:write',
    'order:update',
    'prescription:read',
    'prescription:update',
    'inventory:read',
    'inventory:write',
    'inventory:update',
    'content:read',
    'content:write',
    'content:update',
    'content:delete',
    'settings:read',
    'settings:write',
    'settings:update',
    'customer:read',
    'customer:write',
    'user:read',
    'user:write',
    'user:update',
    'dashboard:read',
    'audit:read',
    'inquiry:read',
    'inquiry:update',
  ],
  superAdmin: ['*'],
};

export const roles = Object.keys(allRoles);

export const roleRights = new Map(Object.entries(allRoles));

export const staffRoles = ['staff', 'pharmacist', 'manager', 'admin', 'superAdmin'] as const;
